### ISSUE TITLE
About Data Release Time

### ISSUE THREAD

**Issue by Yeah2333** [adept-thu/Dual-Radar#2]
This work is excellent. Is there a specific open-source date for the data？

**Comment by liulin813** [comment]
Our code and data are still being maintained and will be released soon.

**Comment by liulin813** [comment]
we have release the dataset

**Comment by leijobs** [comment]
@liulin813 Hello, I have a question that whether independent researcher can get access to this dataset? Since I have downloaded your liecense.txt and found I looks like a contract between two parties and wonder if someone can get this dataset in personal. Thank you!

**Comment by liulin813** [comment]
Obtaining permission is no problem for you. Just fill in your personal information and signature in the agreement, including email and contact information



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月31日(星期二) 上午9:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [adept-thu/Dual-Radar] About Data Release Time (Issue #2)





 
@liulin813 Hello, I have a question that whether independent researcher can get access to this dataset? Since I have downloaded your liecense.txt and found I looks like a contract between two parties and wonder if someone can get this dataset in personal. Thank you!

**Comment by Ianpengg** [comment]
Hello, I have the same question: the license.doc appears to be a contract between two parties. Where should I sign my personal information? Is it in the region shown in the figure below? Thank you for your assistance!
![image](https://github.com/adept-thu/Dual-Radar/assets/88025855/e20a6a9e-a98c-4df5-af92-bcc9308a8da5)
